version: 0.2

phases:
  install:
    commands:
    # Upgrade AWS CLI to the latest version
    - pip install --upgrade pip
    - pip install --upgrade awscli
    - ls
  pre_build:
    commands:
  build:
    commands:
    - aws --version
    # Copy across the contents of the git repo over to S3
    - aws s3 sync .  s3://worklog.fyp.robertcurran.uk
    # Clear the CloudFront Cache with an invalidation request
    # to do
